# Generated by Django 4.1.2 on 2023-02-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('person_name', models.CharField(max_length=100, verbose_name='İsminiz')),
                ('branch_name', models.CharField(max_length=100, verbose_name='İsminiz')),
                ('email', models.CharField(max_length=100, verbose_name='E-Posta Adresiniz')),
                ('yemeksepeti_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='YemekSepeti Komisyon Tutarı')),
                ('getiryemek_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GetirYemek Komisyon Tutarı')),
                ('trendyolyemek_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TrendyolYemek Komisyon Tutarı')),
                ('creditcards_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kredi Kartları Komisyon Tutarı')),
                ('foodcards_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yemek Kartları Komisyon Tutarı')),
                ('branchdrink_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Meşrubat Giderleri')),
                ('branchayranyoghurt_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ayran ve Yoğurt Giderleri')),
                ('branchbread_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ekmek Giderleri')),
                ('branchkitchen_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Şube İçi Mutfak Giderleri')),
                ('branchconsumables_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Şube İçi Sarf Kullanım')),
                ('branchutility_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Elektrik, Su, Doğalgaz')),
                ('branchrent_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kira ve Stopaj Toplamı')),
                ('branchinternet_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Telefon, İnternet, Muhasebe vb.')),
                ('manager_count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yönetici Personel Kişi Sayısı')),
                ('manager_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yönetici Personel Giderleri')),
                ('staff_count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İç Personel Kişi Sayısı')),
                ('staff_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İç Personel Giderleri')),
                ('courier_count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kurye Kişi Sayısı')),
                ('courier_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Motor ve Kurye Giderleri')),
            ],
        ),
    ]
