# Generated by Django 4.1.2 on 2023-02-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmonthlydata',
            name='re_email',
            field=models.CharField(max_length=100, null=True, verbose_name='Tekrar E-Posta Adresiniz'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branch_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Şubeniz'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='person_name',
            field=models.CharField(max_length=100, verbose_name='Adınız Soyadınız'),
        ),
    ]
