# Generated by Django 4.1.2 on 2023-02-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branchmonthlydata_re_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchayranyoghurt_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ayran ve Yoğurt Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchbread_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ekmek Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchconsumables_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Şube İçi Sarf Kullanım'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchdrink_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Meşrubat Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchinternet_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Telefon, İnternet, Muhasebe vb.'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchkitchen_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Şube İçi Mutfak Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchrent_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Kira ve Stopaj Toplamı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='branchutility_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Elektrik, Su, Doğalgaz'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='courier_count',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Kurye Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='courier_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Motor ve Kurye Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='creditcards_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Kredi Kartları Komisyon Tutarı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='foodcards_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Yemek Kartları Komisyon Tutarı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='getiryemek_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='GetirYemek Komisyon Tutarı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='manager_count',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Yönetici Personel Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='manager_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Yönetici Personel Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='staff_count',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='İç Personel Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='staff_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='İç Personel Giderleri'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='trendyolyemek_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='TrendyolYemek Komisyon Tutarı'),
        ),
        migrations.AlterField(
            model_name='branchmonthlydata',
            name='yemeksepeti_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='YemekSepeti Komisyon Tutarı'),
        ),
    ]
