from django import forms
from .models import CenterCommentData

class CenterCommentDataForm(forms.Form):
    total_comment                           = forms.DecimalField(max_value=1000000,label="Toplam Yorum Sayısı")
    total_negative_comment                  = forms.DecimalField(max_value=1000000,label="Toplam Olumsuz Yorum Sayısı")
    total_center_negative_comment           = forms.DecimalField(max_value=1000000,label="Toplam Merkez Olumsuz Yorum Sayısı")
    total_branch_negative_comment           = forms.DecimalField(max_value=1000000,label="Toplam Şube Olumsuz Yorum Sayısı")
    spice_problems                          = forms.DecimalField(max_value=1000000,label="Baharat Fazlalığı")
    price_problems                          = forms.DecimalField(max_value=1000000,label="Fiyat Fazlalığı ve Zam Yapılması")
    portion_problems                        = forms.DecimalField(max_value=1000000,label="Porsiyon Azlığı")
    chicken_skin_problems                   = forms.DecimalField(max_value=1000000,label="Tavuğun Derili ve Kıkırdaklı Olması")
    fabrication_problems                    = forms.DecimalField(max_value=1000000,label="Ürünlerin Fabrikasyon Gibi Olması")
    vegatables_problems                     = forms.DecimalField(max_value=1000000,label="Sebze Ürünlerinin İyi Yıkanmamış Olması")
    foodcard_problems                       = forms.DecimalField(max_value=1000000,label="Yemek Kartı Kullanılmaması")
    chicken_unbaked_problems                = forms.DecimalField(max_value=1000000,label="Tavuğun Yeteri Kadar Pişmemesi")
    stuffed_unbaked_problems                = forms.DecimalField(max_value=1000000,label="Dolmanın Yeteri Kadar Pişmemesi")
    sickness_problems                       = forms.DecimalField(max_value=1000000,label="Yemekten Sonra Rahatsızlık Hissi")
    package_fall_problems                   = forms.DecimalField(max_value=1000000,label="Paketin Açılması ve Dökülmesi")
    meat_crackling_problems                 = forms.DecimalField(max_value=1000000,label="Etin, Köftenin Kıkırdaklı ve Sinirli Olması")
    salt_problems                           = forms.DecimalField(max_value=1000000,label="Yemeklerde Tuz Oranının Fazla Olması")
    oil_problems                            = forms.DecimalField(max_value=1000000,label="Yemeklerin Fazla Yağlı Olması")
    fermantation_problems                   = forms.DecimalField(max_value=1000000,label="Yemekte Ekşime vb. Problemler")
    cold_service_problems                   = forms.DecimalField(max_value=1000000,label="Yemeğin Soğuk Gelmesi")
    forgot_problems                         = forms.DecimalField(max_value=1000000,label="Eksik veya Yanlış Ürün Gelmesi")
    late_problems                           = forms.DecimalField(max_value=1000000,label="Yemeğin Geç Gelmesi")
    note_problems                           = forms.DecimalField(max_value=1000000,label="Notların Yeteri Kadar Dikkate Alınmaması")
    bread_set_problems                      = forms.DecimalField(max_value=1000000,label="Servis Setinin veya Ekmeğin Unutulması")
    courier_problems                        = forms.DecimalField(max_value=1000000,label="Kuryenin Kaba Olması vb.")
    receipt_problems                        = forms.DecimalField(max_value=1000000,label="Fiş Getirilmemesi vb. Problemler")