from django.db import models

class CenterCommentData(models.Model):
    total_comment= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    total_negative_comment= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    total_center_negative_comment= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    total_branch_negative_comment= models.DecimalField(decimal_places=2, max_digits=10, null=True)

    spice_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    price_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    portion_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    chicken_skin_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    fabrication_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    vegatables_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    foodcard_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    chicken_unbaked_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    stuffed_unbaked_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    sickness_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    package_fall_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    meat_crackling_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    salt_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    oil_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    fermantation_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    cold_service_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    forgot_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    late_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    note_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    bread_set_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    courier_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)
    receipt_problems= models.DecimalField(decimal_places=2, max_digits=10, null=True)